# Generated by Django 3.1 on 2020-12-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=50)),
                ('CustomerPhone', models.CharField(max_length=10, unique=True)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('CustomerAddress', models.CharField(max_length=255)),
                ('UserName', models.CharField(max_length=32, unique=True)),
                ('Password', models.CharField(max_length=32)),
                ('DateOfBirth', models.DateTimeField(default='1900/01/01')),
                ('Gender', models.CharField(default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('FoodID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('FoodName', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Description', models.TextField(null=True)),
                ('Rating', models.FloatField()),
                ('Img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('OrderStatus', models.IntegerField(default=0)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentMethod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('RestaurantID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('RestaurantName', models.CharField(max_length=50)),
                ('RestaurantAddress', models.CharField(max_length=255)),
                ('RestaurantPhone', models.CharField(max_length=10)),
                ('BusinessHour', models.CharField(default='00:00 - 00:00', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('ShipperID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ShipperName', models.CharField(max_length=50)),
                ('ShipperPhone', models.CharField(max_length=10)),
                ('ShipperStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Serve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.FloatField(default=0)),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.food')),
                ('RestaurantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.food')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='PaymentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='ShipperID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.shipper'),
        ),
    ]
